// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kiwviahzlghulnajudrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtpd3ZpYWh6bGdodWxuYWp1ZHJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDgzNzEsImV4cCI6MjA2ODE4NDM3MX0.aFcWlPmOkWE7x9c0tv0OWOIso_24sLX0o2UnjHJrRV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});