// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://crpalakzdzvtgvljlutd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNycGFsYWt6ZHp2dGd2bGpsdXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MTczMzAsImV4cCI6MjA3MTk5MzMzMH0.oAwkJGpM1rhF6GVav8XMaiZozrku-WUe9JHCYkcjmkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});